(* This file was autogenerated; don't edit it by hand *)

let tests () = OUnit.TestList [
    Async_condition.ounit_tests ();
    Async_or_error.ounit_tests ();
    Async_stream.ounit_tests ();
    Backpatched.ounit_tests ();
    Clock.ounit_tests ();
    Clock_event.ounit_tests ();
    Config.ounit_tests ();
    Debug.ounit_tests ();
    Deferred.ounit_tests ();
    Deferred_intf.ounit_tests ();
    Deferred_std.ounit_tests ();
    Events.ounit_tests ();
    Execution_context.ounit_tests ();
    Handler.ounit_tests ();
    Import.ounit_tests ();
    Ivar.ounit_tests ();
    Job.ounit_tests ();
    Jobs.ounit_tests ();
    Lazy_deferred.ounit_tests ();
    Monitor.ounit_tests ();
    Pipe.ounit_tests ();
    Priority.ounit_tests ();
    Raw_clock_event.ounit_tests ();
    Raw_deferred.ounit_tests ();
    Raw_handler.ounit_tests ();
    Raw_ivar.ounit_tests ();
    Raw_monitor.ounit_tests ();
    Raw_scheduler.ounit_tests ();
    Raw_stream.ounit_tests ();
    Raw_tail.ounit_tests ();
    Scheduler.ounit_tests ();
    Std.ounit_tests ();
    Tail.ounit_tests ();
    Test.ounit_tests ();
    Thread_pool.ounit_tests ();
    Throttle.ounit_tests ();
    Unregister.ounit_tests ();
    Work_group.ounit_tests ();
];;

let run () =  ignore (OUnit.run_test_tt_main (tests ()):OUnit.test_result list)
